<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
	public function findByReservationDate($date)
	{
		$qb = $this->createQueryBuilder('r');

		$qb
			->where('r.reservation_date = :date')
			->setParameter('date', $date);

		$query = $qb->getQuery();
		$results = $query->getResult();

		return $results;
	}
}
